### ISSUE TITLE
non portable scripts - openCL device name must be explicit, suggest auto selection

### ISSUE THREAD

**Issue by chalkie666** [clij/clij#18]
I notice that running from imageJ GUI, you get the chance to select which openCL device to use, then this is passed to the plugin, so the function is executed there. That is certainly a "good thing" 
However, if I write an IJ macro or javascript etc, the openCL device name is hardcoded in there. 
If i try to run the script on another machine with different openCL device name, then it probably fails - right? The naive user wont know how to fix it.  
Consider a situation, where the "best" openCL device is determined at run time, as done by clear volume, and that is then assigned to device name  "auto", so if no openCL device name is supplied in a script command, then the one chosen as auto is used by default Then scripts can be shared and run without modification?

**Comment by haesleinhuepf** [comment]
Hi @chalkie666 

good point. Thanks for bringing this up.
In case you enter you enter a device like "geforce" in a script which is run on a computer which has no device with this name, it falls back to the first GPU it finds in the device list. That's btw also the default selection in dialogs. So we're kind of safe here.

Furthermore, ClearVolume and CLIJ are both built on ClearCL which allows the selection of the "best" device as you mentioned. However, this feature currently has issues on linux and the 8th generation of Intels core CPUs. That's why it's deactivated at the moment. 

CLIJ runs automatically on the first GPU device it finds. The user can choose another one if he feels like. I'm afraid we need to keep it like this for the moment.

Again, thanks for the feedback and for testing it. That's very well appreciated!

I keep the issue open so that we can keep an eye on this.

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
Addendum: leave the device empty and it'll be the "auto" feature you suggested 😉
