### ISSUE TITLE
Feature request - 3D project on GPU

### ISSUE THREAD

**Issue by mnqslbs2** [clij/clij#20]
Excellent work @haesleinhuepf 
This is a real time saver. I wonder could you implement 3D Project on the GPU this would be great.
Thanks, Ben

**Comment by haesleinhuepf** [comment]
Hey Ben @mnqslbs2 ,

thanks for the feedback! The idea of a 3D-projection as in ImageJ is excellent! This is actually something perfect for OpenCL that should run in the GPU like a snap of ones finger. I'll think about it. Actually the code should very similar to the radial projection plugin. 
https://github.com/clij/clij/blob/3aecf2ca34b649621dbbce32b797492c314bce8d/src/main/java/net/haesleinhuepf/clij/macro/modules/ResliceRadial.java

Stay tuned!

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
Hi Ben @mnqslbs2 ,

a small step forward: If you update your Fiji, there are now rotate3D and translate3D methods which one needs in order to get a 3D-projection macro running. You find it here:
https://github.com/clij/clij/blob/master/src/main/macro/project3D.ijm

I will put everything in a proper CLIJ method (with anisotropy and interpolation handling) at some point, but feel free to play with the macro. It's actually a nice example of some more methods for which no example macros existed yet. Thus, again thanks a lot for this feature request! I keep you posted as soon as a more sophisiticated method is ready to try!
![rot](https://user-images.githubusercontent.com/12660498/51638824-b628eb80-1f5f-11e9-8f00-71fe9d1bbaff.gif)


Cheers,
Robert
