### ISSUE TITLE
Mean Z projection not giving correct results

### ISSUE THREAD

**Issue by hiimwilson** [clij/clij#35]
Hey there, 

I was trying to run a Mean Z projection on some timeseries image data of mine and CLIJ is throwing some interesting results. Not sure if this is a calculation error or something else. Bu the results do not match the native FIJI output. This does not appear to happen on the StDev, max, min z projections. A similar thing does happens with sumZP, but only when the summation image exceeds the bit depth of the source image (which it often does for large images, but I typically use the MeanIP to get around that). 

The particular stack is a 16-bit depth .nd2 opened imported with bioformats as a virtual stack, if that has any relevance. 

![image](https://user-images.githubusercontent.com/10383579/69886122-12f2e200-12a6-11ea-8e04-a9363b2de0ac.png)

All the best, 
Wilson

**Comment by haesleinhuepf** [comment]
Hey @hiimwilson ,

thanks for this bug report! There was an overflow when summing pixels over Z. This bug is fixed in clij 1.4.3. Would you mind updating your Fiji, testing it and reporting back if it works now? If not, it would be nice if you could send me a small example image to reproduce the issue.

Thanks again! It's a pleasure working with you :-)

Cheers,
Robert

**Comment by imagejan** [comment]
For the record, the commit fixing this is https://github.com/clij/clij-core/commit/7b66a30b2da6fb1553f997747425cc29c9825d75, right?

**Comment by hiimwilson** [comment]
sorry for the delay. looks like its all working well! Thanks for fixing so quickly! :)
