### ISSUE TITLE
Image clip on affine transform 3D on GPU

### ISSUE THREAD

**Issue by BMillis** [clij/clij#36]
Appear to get image/stack clipping on the shear component of an affine transform.

**Comment by haesleinhuepf** [comment]
Hey @BMillis,

shearing is actually meant to deform the image in a way so that it doesn't fit in the image size of the original. Just like corners disappear when rotating an image. I'd recommend creating a target image in advance with larger dimensions. You may also want to combine the shearing with a translation.

Does that help? If not, please share some details of your workflow 😉

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
In case you're working on deskewing SCAPE image data, this might help: 
https://github.com/SpimCat/unsweep/blob/master/src/main/java/net/haesleinhuepf/spimcat/unsweep/Unsweep.java#L43-L53

😉

Cheers,
Robert
