### ISSUE TITLE
running benchmarks from the command line

### ISSUE THREAD

**Issue by psteinb** [clij/clij#8]
just cloned this repo and wanted to give it a spin from the CL. E.g. [BenchmarkingDemo.java](https://github.com/ClearControl/clearclij/blob/master/src/main/java/clearcl/imagej/demo/BenchmarkingDemo.java) is apparently not included in any `mvn` goals. So I tried from the command-line:

```
$ java -cp ./target/classes/:${HOME}/software/imglib2/target/classes:${HOME}/software/imglib2-algorithm/target/classes/:${HOME}/software/fiji/bundled/jars/imagej-2.0.0-rc-68.jar:${HOME}/software/fiji/bundled/jars/scijava-common-2.75.0.jar:${HOME}/development/clearcl/build/classes/ net.haesleinhuepf.imagej.demo.BenchmarkingDemo
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[ERROR] Could not load icon for class: net.haesleinhuepf.imagej.macro.CLIJMacroExtensions
Exception in thread "main" java.lang.NoClassDefFoundError: clearcl/backend/ClearCLBackendInterface
	at net.haesleinhuepf.imagej.demo.BenchmarkingDemo.main(BenchmarkingDemo.java:47)
Caused by: java.lang.ClassNotFoundException: clearcl.backend.ClearCLBackendInterface
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```
Ideas on how this can be fixed? In the hand, running the benchmarks through a maven goal would be lovely for collecting timing information from more platforms.

**Comment by haesleinhuepf** [comment]
Hey @psteinb ,

I found a way to do this. It's a bit from the back through the chest into the eye but anyway a starting point:

To get started, you need a fresh Fiji installation. Enter its path here (you need to adapt some more paths, see below):
https://github.com/haesleinhuepf/clearclij/blob/master/installBenchmark.bat

Then, run the batch file to install CLIJ into your Fiji. Afterwards, you can run benchmarks from command line:
https://github.com/haesleinhuepf/clearclij/blob/master/benchmark.bat

This batch file will call a macro, which calls a plugin, which calls a macro. That sounds seriously sick and is due to the fact, that the benchmarking.ijm macro cannot be called directly because of a bug deep inside ImageJ. Furthermore, inside the plugin, a path needs to be adapted to run on any PC:
https://github.com/haesleinhuepf/clearclij/blob/master/src/main/java/net/haesleinhuepf/imagej/utilities/BenchmarkExecutorPlugin.java#L30 

Sorry for the hacky solution. As soon as I find a better one, I let you know. I see that this is very important to have an easy way to check everything on many systems. Unfortunately, that's the only way I found so far. A potential alternative would be using `mvn -test`. I will clean up tests soon in order to make this work as well.

Thanks for your support!

Cheers,
Robert

**Comment by psteinb** [comment]
I'll see to testing that. As an alternative to using the tests for benchmarking, using projects like [jmh](https://openjdk.java.net/projects/code-tools/jmh/) may be handy.
@skalarproduktraum IIRC, you have used jmh. Any thoughts or experiences?
According to this [nice post](https://stackoverflow.com/a/7445378), there are quite some related projects out there.

**Comment by skalarproduktraum** [comment]
@psteinb jmh is nice, and for the vectorisation stuff, it was quite helpful. That being said, it's mostly targeted to micro-benchmarking, hence the name 😄 You'll need to check whether it's a good fit.

@haesleinhuepf I think it'd be a good idea to move demos to the test directory as well, if you don't need them in the GUI. You can give them a special name (e.g. containing `Demo` or `Example`) that does not get included into `mvn test` by default via a configuration of the `maven-surefire-plugin`:

```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-surefire-plugin</artifactId>
  <configuration>
    <includes>
      <include>**/*Tests.*</include>
    </includes>

    <excludes>
      <exclude>**/*Example.*</exclude>
    </excludes>
  </configuration>
</plugin>
```

EDIT: Fix code formatting.

**Comment by haesleinhuepf** [comment]
benchmarking was moved to a separate repository and runs from command line. closing this for now
